parameters:
#    swd_route_configuration.example.class: Swd\Bundle\RouteConfigurationBundle\Example

services:
#    swd_route_configuration.example:
#        class: %swd_route_configuration.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
