parameters:
    swd_route_configuration.class: Swd\Bundle\RouteConfigurationBundle\EventListener\RouterListener

services:
    swd_route_configuration.router_listener:
        class: %swd_route_configuration.class%
        arguments: 
            router: @router
            logger: @logger
        tags: 
            - { name: "kernel.event_listener", event: "kernel.request", method:"onKernelRequest" }
            - { name: "monolog.logger", channel: "request" }
            
